trigger:
  branches:
    include:
      - main
      - master
      - release/current
      - release/next

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: guardian
      type: github
      name: LeonelIntegrationXpert/release-flow-guardian-core
      endpoint: github-service-connection
      ref: refs/heads/main

extends:
  template: azure/templates/raml-ci.yml@guardian
  parameters:
    configPath: release/guardian.config.yml
    guardianRef: main
