name: Release Flow Guardian

on:
  pull_request:
    branches:
      - main
      - master
      - release/current
      - release/next
  push:
    branches:
      - main
      - master
      - release/current
      - release/next
  workflow_dispatch:
    inputs:
      publish_exchange:
        description: "Publicar no Exchange?"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  guardian:
    uses: LeonelIntegrationXpert/release-flow-guardian-core/.github/workflows/raml-ci-exchange.yml@main
    with:
      config-path: release/guardian.config.yml
      guardian-ref: main
      publish-exchange: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_exchange == 'true') }}
    secrets:
      ANYPOINT_CONNECTED_APP_CLIENT_ID: ${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_ID }}
      ANYPOINT_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_SECRET }}
      ANYPOINT_ORG: ${{ secrets.ANYPOINT_ORG }}
      ANYPOINT_HOST: ${{ secrets.ANYPOINT_HOST }}
      EXCHANGE_GROUP_ID: ${{ secrets.EXCHANGE_GROUP_ID }}
